# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstall', '0003_auto_20171130_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title', 'image', 'year', 'count')},
        ),
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
